[package]
name = "conoha"
version = "0.1.0"
authors = ["Mitsuki Watanabe <ix5231if@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = "2"
interactor = "0.1"
